<?php
/**
 * Ur-Sltn Webgains
 *
 * NOTICE OF LICENSE
 *
 * Private Proprietary Software (https://ur-sltn.com/terms-of-service.php)
 *
 * @category   UrSltn
 * @package    UrSltn_Webgains
 * @copyright  Copyright (c) 2016 Ur-Sltn LTD (https://ur-sltn.com)
 * @license    https://ur-sltn.com/terms-of-service.php  Private Proprietary Software
 * @author     Shaughn Le Grange - Hatlen <me@shaughn.pro>
 */
?>
<?php /** @var UrSltn_Webgains_Block_Checkout_Success_Tracking $this */ ?>
<?php if ($this->helper('ursltn_webgains')->isTrackingActive()): ?>
    <?php $trackingCode = $this->getTrackingCode(); ?>

    <?php if (!empty($trackingCode)): ?>
        <?php $universalVar = @json_encode($trackingCode); ?>
        <?php if ($universalVar): ?>
            <script>
                //<![CDATA[
                window.universal_variable = <?php echo $universalVar; ?>;
                //]]>
            </script>
        <?php endif; ?>
    <?php endif; ?>
    <script src="//d3c3cq33003psk.cloudfront.net/opentag-163059-webgains.js" async defer></script>
<?php endif; ?>